
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 1.00.a
 PARAMETER PROC_INSTANCE = ppc405_0
 PARAMETER stdin = opb_uart_serial
 PARAMETER stdout = opb_uart_serial
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu_ppc405
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = ppc405_0
 PARAMETER COMPILER = powerpc-eabi-gcc
 PARAMETER ARCHIVER = powerpc-eabi-ar
 PARAMETER CORE_CLOCK_FREQ_HZ = 300000000
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = opb_v20_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 2.01.a
 PARAMETER HW_INSTANCE = opb_gpio_helios
END

BEGIN DRIVER
 PARAMETER HW_INSTANCE = plb2opb_bridge_0
 PARAMETER DRIVER_NAME = plb2opb
 PARAMETER DRIVER_VER = 1.00.a
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = plb_bram_if_cntlr_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = plb_v34_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 1.01.a
 PARAMETER HW_INSTANCE = opb_uart_serial
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 1.01.a
 PARAMETER HW_INSTANCE = opb_uart_wireless
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = sdram
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = plb_sdram_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = opb_pwm_ctrl
 PARAMETER HW_INSTANCE = opb_pwm
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = opb_quad_encoder
 PARAMETER HW_INSTANCE = opb_encoder
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = plb_camera
 PARAMETER HW_INSTANCE = plb_cam0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = plb_usb
 PARAMETER DRIVER_VER = 1.00.d
 PARAMETER HW_INSTANCE = plb_usb_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = opb2plb
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = opb2plb_bridge_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = intc
 PARAMETER DRIVER_VER = 1.00.c
 PARAMETER HW_INSTANCE = opb_intc_0
END


