
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 8.1.02 EDK_I.20.4
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver parameters
*
*******************************************************************/

#define STDIN_BASEADDRESS 0x40620000
#define STDOUT_BASEADDRESS 0x40620000

/******************************************************************/


/******************************************************************/

#define XPAR_PLB_SDRAM_0_BASEADDR 0x00000000
#define XPAR_PLB_SDRAM_0_HIGHADDR 0x01FFFFFF

/******************************************************************/

#define XPAR_PLB_BRAM_IF_CNTLR_0_BASEADDR 0xffff0000
#define XPAR_PLB_BRAM_IF_CNTLR_0_HIGHADDR 0xffffffff

/******************************************************************/

#define XPAR_XPLB_CAMERA_NUM_INSTANCES 1
#define XPAR_PLB_CAM0_BASEADDR 0xC6400000
#define XPAR_PLB_CAM0_HIGHADDR 0xC640FFFF

/******************************************************************/

#define XPAR_PLB_USB_NUM_INSTANCES 1
#define XPAR_PLB_USB_0_DEVICE_ID 0
#define XPAR_PLB_USB_0_BASEADDR 0xCBC00000
#define XPAR_PLB_USB_0_HIGHADDR 0xCBC0FFFF

/******************************************************************/

#define XPAR_XUARTLITE_NUM_INSTANCES 2
#define XPAR_OPB_UART_SERIAL_BASEADDR 0x40620000
#define XPAR_OPB_UART_SERIAL_HIGHADDR 0x4062FFFF
#define XPAR_OPB_UART_SERIAL_DEVICE_ID 0
#define XPAR_OPB_UART_SERIAL_BAUDRATE 115200
#define XPAR_OPB_UART_SERIAL_USE_PARITY 0
#define XPAR_OPB_UART_SERIAL_ODD_PARITY 0
#define XPAR_OPB_UART_SERIAL_DATA_BITS 8
#define XPAR_OPB_UART_WIRELESS_BASEADDR 0x40600000
#define XPAR_OPB_UART_WIRELESS_HIGHADDR 0x4060FFFF
#define XPAR_OPB_UART_WIRELESS_DEVICE_ID 1
#define XPAR_OPB_UART_WIRELESS_BAUDRATE 57600
#define XPAR_OPB_UART_WIRELESS_USE_PARITY 0
#define XPAR_OPB_UART_WIRELESS_ODD_PARITY 0
#define XPAR_OPB_UART_WIRELESS_DATA_BITS 8

/******************************************************************/

#define XPAR_XGPIO_NUM_INSTANCES 1
#define XPAR_OPB_GPIO_HELIOS_BASEADDR 0x40000000
#define XPAR_OPB_GPIO_HELIOS_HIGHADDR 0x4000FFFF
#define XPAR_OPB_GPIO_HELIOS_DEVICE_ID 0
#define XPAR_OPB_GPIO_HELIOS_INTERRUPT_PRESENT 0
#define XPAR_OPB_GPIO_HELIOS_IS_DUAL 0

/******************************************************************/

#define XPAR_XPWM_CTRL_NUM_INSTANCES 1
#define XPAR_OPB_PWM_BASEADDR 0x73C00000
#define XPAR_OPB_PWM_HIGHADDR 0x73C0FFFF

/******************************************************************/

#define XPAR_XQUAD_ENCODER_NUM_INSTANCES 1
#define XPAR_OPB_ENCODER_BASEADDR 0x7A400000
#define XPAR_OPB_ENCODER_HIGHADDR 0x7A40FFFF

/******************************************************************/

#define XPAR_INTC_MAX_NUM_INTR_INPUTS 4
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_USE_DCR 0
#define XPAR_XINTC_NUM_INSTANCES 1
#define XPAR_OPB_INTC_0_BASEADDR 0x41200000
#define XPAR_OPB_INTC_0_HIGHADDR 0x4120FFFF
#define XPAR_OPB_INTC_0_DEVICE_ID 0
#define XPAR_OPB_INTC_0_KIND_OF_INTR 0x0000000F

/******************************************************************/

#define XPAR_INTC_SINGLE_BASEADDR 0x41200000
#define XPAR_INTC_SINGLE_HIGHADDR 0x4120FFFF
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_OPB_INTC_0_DEVICE_ID
#define XPAR_PLB_CAM0_INTERRUPT_MASK 0X000001
#define XPAR_OPB_INTC_0_PLB_CAM0_INTERRUPT_INTR 0
#define XPAR_PLB_USB_0_INTERRUPT_MASK 0X000002
#define XPAR_OPB_INTC_0_PLB_USB_0_INTERRUPT_INTR 1
#define XPAR_OPB_UART_SERIAL_INTERRUPT_MASK 0X000004
#define XPAR_OPB_INTC_0_OPB_UART_SERIAL_INTERRUPT_INTR 2
#define XPAR_OPB_UART_WIRELESS_INTERRUPT_MASK 0X000008
#define XPAR_OPB_INTC_0_OPB_UART_WIRELESS_INTERRUPT_INTR 3

/******************************************************************/

#define XPAR_CPU_PPC405_CORE_CLOCK_FREQ_HZ 300000000

/******************************************************************/

